using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BetterServer
{
    public enum PacketType : byte
    {
        SERVER_PLAYER_JOINED,
        SERVER_PLAYER_LEFT,
        SERVER_PLAYER_INFO,
        SERVER_PLAYER_FORCE_DISCONNECT,
        SERVER_LOBBY_READY_STATE,
        SERVER_LOBBY_EXE,
        SERVER_LOBBY_COUNTDOWN,
        SERVER_LOBBY_EXE_CHANGE,
        SERVER_LOBBY_CHARACTER_CHANGE,
        SERVER_LOBBY_CHARACTER_RESPONSE,
        SERVER_LOBBY_GAME_START,
        SERVER_LOBBY_PLAYER,

        SERVER_GAME_EXE_WINS,
        SERVER_GAME_SURVIVOR_WIN,
        SERVER_GAME_SPAWN_RING,
        SERVER_GAME_PLAYER_ESCAPED,
        SERVER_GAME_BACK_TO_LOBBY,
        SERVER_GAME_TIME_SYNC,
        SERVER_GAME_TIME_OVER,
        SERVER_GAME_DEATHTIMER_TICK,
        SERVER_GAME_DEATHTIMER_END,

        SERVER_REQUEST_INFO,
        SERVER_HEARTBEAT,
        SERVER_PONG,

        SERVER_FORCE_DAMAGE,
        SERVER_GAME_RING_READY,
        SERVER_PLAYER_BACKTRACK,

        // Entities
        SERVER_TPROJECTILE_STATE,
        SERVER_ETRACKER_STATE,
        SERVER_RMZSLIME_STATE,
        SERVER_RMZSLIME_RINGBONUS,
        SERVER_LCEYE_STATE,
        SERVER_LCCHAIN_STATE,
        SERVER_NPCONTROLLER_STATE,
        SERVER_KAFMONITOR_STATE,
        SERVER_YCRSMOKE_STATE,
        SERVER_YCRSMOKE_READY,
        SERVER_MOVINGSPIKE_STATE,
        SERVER_RING_STATE,
        SERVER_RING_COLLECTED,
        SERVER_ACT9WALL_STATE,

        // Entity actions
        CLIENT_ETRACKER,
        CLIENT_ETRACKER_ACTIVATED,
        CLIENT_TPROJECTILE,
        CLIENT_TPROJECTILE_HIT,
        CLIENT_RMZSLIME_HIT,
        CLIENT_LCEYE_REQUEST_ACTIVATE,
        CLIENT_KAFMONITOR_ACTIVATE,
        CLIENT_RING_COLLECTED,

        CLIENT_LOBBY_READY_STATE,
        CLIENT_REQUESTED_INFO,
        CLIENT_PLAYER_DATA,
        CLIENT_PLAYER_HURT,
        CLIENT_SOUND_EMIT,
        CLIENT_PING,

        CLIENT_REVIVAL_PROGRESS,

        CLIENT_REQUEST_CHARACTER,
        CLIENT_PLAYER_DEATH_STATE,
        CLIENT_PLAYER_ESCAPED,
        CLIENT_LOBBY_PLAYERS_REQUEST,
        CLIENT_CREAM_SPAWN_RINGS,
        CLIENT_RING_SPAWNED2,
        CLIENT_SPAWN_EFFECT,
        CLIENT_CHAT_MESSAGE
    }
}
